#pragma once
#include"EnumHelper.h"
//! InitActivation Flags
typedef enum class _NVAPI_STEREO_INIT_ACTIVATION_FLAGS
{
  [EnumDescriptionAttribute("NVAPI_STEREO_INIT_ACTIVATION_IMMEDIATE: ")]
  NVAPI_STEREO_INIT_ACTIVATION_IMMEDIATE = 0X00,
  [EnumDescriptionAttribute("NVAPI_STEREO_INIT_ACTIVATION_DELAYED: ")]
  NVAPI_STEREO_INIT_ACTIVATION_DELAYED = 0x01,
} NVAPI_STEREO_INIT_ACTIVATION_FLAGS;